config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "toppages#index"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to: "users#new"
  resources :users, only: [:show, :new, :create]
  
  resources :items 

  resources :items do
    member do
      resources :chats, only: [:index, :create]
    end
  end
  
  resources :chats, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :item
  
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  
  validates :content, presence: true, length: { maximum: 400 }

  mount_uploader :image, ImageUploader
  
  validates :image, presence: true
  
  has_many :chats, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :items
  has_many :chats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end  
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  def index
    @item = Item.find(params[:id])
    @chat = @item.chats.build
    @chats = @item.chats.order(id: :desc)
  end

  def create
    @item = Item.find(params[:id])
    @chats = @item.chats.order(id: :desc)
    @chat = @item.chats.build(chat_params)
    @chat.user_id = current_user.id
    if @chat.save
      flash[:success] = "メッセージを送信しました。"
      redirect_to chats_path 
    else
      flash.now[:danger] = "メッセージの送信に失敗しました。"
      render :index
    end  
  end

  def destroy
    @chat.destroy
    flash[:success] = "メッセージを削除しました。"
    redirect_back(fallback_location: chats_path)
  end
  
  private
  
  def chat_params
    params.require(:chat).permit(:content)
  end  
  
  def correct_user
    @chat = current_user.chats.find_by(id: params[:id])
    unless @chat
      redirect_to chats_path
    end
  end  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :destroy]
  
  def index
    @items = Item.order(id: :desc).page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end
  
  def create
    @item = current_user.items.build(item_params)
    if @item.save
      flash[:success] = "商品を投稿しました。"
      redirect_to items_path
    else
      flash.now[:danger] = "商品の投稿に失敗しました。"
      render :new
    end  
  end

  def destroy
    @item.destroy
    flash[:success] = "商品を削除しました。"
    redirect_back(fallback_location: items_path)
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    
    if @item.update(item_params)
      flash[:success] = "商品は正常に更新されました。"
      redirect_to @item
    else
      flash.now[:danger] = "商品は更新されませんでした。"
      render :edit
    end  
  end  
  
  private
  
  def item_params
    params.require(:item).permit(:content, :image)
  end  
  
  def correct_user
    @item = current_user.items.find_by(id: params[:id])
    unless @item
      redirect_to items_path
    end
  end  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = "ログインに成功しました。"
      redirect_to @user
    else
      flash.now[:danger] = "ログインに失敗しました。"
      render :new
    end  
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました。"
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      
      session[:user_id] = @user.id
      return true
    else
      
      return false
    end
  end  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  
  def show
    @user = User.find(params[:id])
    @items = @user.items.order(id: :desc).page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザー登録しました"
      redirect_to @user
    else
      flash.now[:danger] = "ユーザー登録に失敗しました"
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end  

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/chats/index.html.erb
<h1>チャット</h1>

<div class="row">
    <aside class="col-sm-4">
      <%= form_with(model: @chat, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
        <div class="form-group">
          <%= f.text_area :content, class: 'form-control', rows: 5 %>
        </div>
        <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
      <% end %>
    </aside>
    <div class="col-sm-8">
      <ul class="list-unstyled">
        <% @chats.each do |chat| %>
          <li class="media mb-3">
            <img class="mr-2 rounded" src="<%= gravatar_url(chat.user, { size: 50 }) %>" alt="">
              <div class="media-body">
                <div>
                  <%= link_to chat.user.name, user_path(chat.user) %> <span class="text-muted">posted at <%= chat.created_at %></span>
                </div>
                <div>
                  <p><%= chat.content %></p>
                </div>
                <div>
                  <% if current_user == chat.user %>
                    <%= link_to "削除", chat, method: :delete, data: {confirm: "You sure?" }, class: "btn btn-danger btn-sm" %>
                  <% end %>
                </div>
              </div>
          </li>
        <% end %>
      </ul>
    </div>  
</div>

app/views/items/_items.html.erb
<ul class="list-unstyled">
      <% items.each do |item| %>
        <li>
          <img class="mr-2 rounded" src="<%= gravatar_url(item.user, { size: 50 }) %>" alt="">
              <div>
                <%= link_to item.user.name, user_path(item.user) %> <span class="text-muted">posted at <%= item.created_at %></span>
              </div>
              <div class="img">
                <p><%= image_tag item.image.url if item.image? %></p>
              </div>
              <div>
                <p><%= item.content %></p>
              </div>
              <div class="mb-3">
                <span><%= link_to"詳細", item_path(item), class: "btn btn-primary btn-sm" %></span>
                <% if current_user == item.user %>
                  <span><%= link_to "削除", item, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %></span>
                <% end %>
              </div>
        </li>
      <% end %>
    <%= paginate items %>
</ul>

app/views/items/edit.html.erb
<h1>商品編集ページ</h1>

<%= form_with(model: @item, local: true) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  
  <%= f.label :image, "画像をアップロード" %>
  <%= f.file_field :image %>
  
  <%= f.label :content, "商品説明" %>
  <%= f.text_area :content, class: "form-control", rows: 10 %>
  
  <%= f.submit "投稿", class: "btn btn-primary btn-block" %>
 <% end %>

app/views/items/index.html.erb
<div class="row">
  <div class="col-sm-3">
    <%= link_to"出品", new_item_path, class: "btn btn-primary btn-block" %>
  </div>
  <div class="col-sm-9">
    <%= render "items", items: @items %>
  </div>
</div>

app/views/items/new.html.erb
<h1>商品投稿ページ</h1>

<%= form_with(model: @item, local: true) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  
  <%= f.label :image, "画像をアップロード" %>
  <%= f.file_field :image %>
  
  <%= f.label :content, "商品説明" %>
  <%= f.text_area :content, class: "form-control", rows: 10 %>
  
  <%= f.submit "投稿", class: "btn btn-primary btn-block" %>
 <% end %> 

app/views/items/show.html.erb
<h1>詳細ページ</h1>

<div>
  <%= link_to @item.user.name, user_path(@item.user) %> <span class="text-muted">posted at <%= @item.created_at %></span>
</div>
<div>
  <p><%= image_tag @item.image.url if @item.image? %></p>
</div>
<div>
  <p><%= @item.content %></p>
</div>
<div>
  <span><%= link_to "チャットへ", chats_path(@item), class: "btn btn-primary btn-sm" %></span>
  <% if current_user == @item.user %>
    <span><%= link_to "編集する", edit_item_path(@item), class: "btn btn-light btn-sm" %></span>
  <% end %>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>  

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <% if logged_in? %>
  <a class="navbar-brand" href="/items">出品一覧</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "My profile", user_path(current_user), class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Logout", logout_path, method: :delete, class: "nav-link" %></li>
    </ul>
  </div>
  <% else %>
  <a class="navbar-brand" href="/">トップページ</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "Signup", signup_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Login", login_path, class: "nav-link" %></li>
    </ul>
  </div>  
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Original</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="original.css">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    
    <div class="container">
      <%= render "layouts/flash_messages" %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<div class="text-center">
  <div class="top">
    <h1>Welcome to Don't throw!</h1>
    <p>このサイトは、東京薬科大学に所属している方でいらなくなった教科<br>
    書、参考書、実験で使ったものなどをここに出品していただいて、ほ<br>
    しい方がいればそれを譲っていただくためのものです。</p>
    <p>出品者は画像と商品の説明を投稿して、ほしい方はその方とチャット<br>
    をしてやりとりをし、実際に会って、モノをいただきます。</p>
    <p>特に6年生は卒業前にいらなくなったものがありましたら是非ここに出<br>
    品していただきたいです。</p>
    <p>ログインするとこの説明は表示されないので注意してください。</p>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render "layouts/error_messages", model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, "Email" %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, "Password" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      
      <%= f.submit "Sign up", class: "btn btn-primary btn-block" %>
    <% end %>  
  </div>
</div>

app/views/users/show.html.erb
<h1>ユーザー詳細ページ</h1>

<div class="row">
  <aside class="col-sm-3">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-sm-9">
    <%= render "items/items", items: @items %>
  </div>  